# Generated by Django 3.2.4 on 2021-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tittle',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
