# Generated by Django 3.2.4 on 2021-08-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_book_tittle'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='tittle',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
