# Generated by Django 3.2.4 on 2021-08-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210801_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
