# Generated by Django 3.2.4 on 2021-08-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
