# Generated by Django 3.2.4 on 2021-08-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
