# Generated by Django 3.2.4 on 2021-08-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20210801_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
